name: Code style
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push: {}
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - version: "3.11"
            check-formatting: "true"
            check-consistency: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          cache: "poetry"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          poetry install -n
      - name: Install missing dependencies
        run: |
          poetry run pip install flake8 mypy
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Lint
        run: |
          poetry run flake8 s3transfer-stubs
          poetry run npx pyright s3transfer-stubs
          poetry run mypy s3transfer-stubs
      - name: Check formatting
        if: ${{ matrix.check-formatting }}
        run: |
          poetry run black --check s3transfer-stubs
          poetry run isort -c s3transfer-stubs
      - name: Stubs consistency check
        if: ${{ matrix.check-consistency }}
        run: |
          poetry run istub -d
