name: Check consistency of stubs
concurrency:
  group: on_timer_check
  cancel-in-progress: true


on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  check-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Poetry
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install poetry pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
      - name: Install latest s3transfer
        run: |
          poetry run pip install -U s3transfer
      - name: Stubs consistency check
        run: |
          poetry run istub
